apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "quarkus-template.labels" . | nindent 4 }}
  name: fight
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fight
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true