{%raw %}
{{- if not (eq .Values.environment "dev") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev{% endraw %}{{ teamid }}{% raw %}-villain-pusher-edit
  namespace: "{{ .Values.namespace.name }}"
subjects:
  - kind: ServiceAccount
    name: dev{% endraw %}{{ teamid }}{% raw %}-villain-image-pusher
    namespace: villain-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
{{- end }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
#  name: dev{% endraw %}{{ teamid }}{% raw %}-{{ .Values.namespace.name }}
  name: villain-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dev{% endraw %}{{ teamid }}{% raw %}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{% endraw %}