apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "fight-ui.labels" . | nindent 4 }}
  name: fight-ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fight-ui
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true