{{- if not (eq .Values.environment "dev") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: "{{ .Values.namespace.name }}"
subjects:
  - kind: ServiceAccount
    name: image-pusher
    namespace: hero-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
{{- end }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev{{ teamid }}-{{ .Values.namespace.name }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dev{{ teamid }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
